Repository jenkinsci/docker-commons-plugin, pull requests merged in 2022-08, with the labels that each got.

#91 Deleting `CredentialsBindingHandler.toBindings`
  src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandler.java
Labels: chore

#86 docker login - get password from stdin
  src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
Labels: bug

#95 Deprecate Release Drafter app in favor of GitHub workflow
  .github/workflows/release-drafter.yml
Labels: chore

#96 Enable dependabot
  .github/dependabot.yml
Labels: chore

#98 Replace deprecated calls
  src/main/java/org/jenkinsci/plugins/docker/commons/DockerImageExtractor.java
  src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
  src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpoint.java
  src/main/java/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprints.java
  src/main/java/org/jenkinsci/plugins/docker/commons/impl/UsernamePasswordDockerRegistryTokenSource.java
  src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsBindingTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsHandlerTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerCredentialsTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerDomainSpecificationTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerServerEndpointTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactoryTest.java
  src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Labels: chore

#99 Use "agent" in the javadoc rather than "slave"
  src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerTool.java
Labels: documentation

#94 Allow to use registry as host and port only to allow to use podman as executable
  src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
  src/test/java/org/jenkinsci/plugins/docker/commons/impl/HostOnlyRegistryKeyMaterialFactoryTest.java
Labels: enhancement

#89 Remove icon-shim
  src/main/resources/org/jenkinsci/plugins/docker/commons/fingerprint/DockerFingerprintAction/index.jelly
Labels: chore

#90 Install docker from stable channel
  src/main/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstaller.java
  src/test/java/org/jenkinsci/plugins/docker/commons/tools/DockerToolInstallerTest.java
Labels: enhancement

#88 [JENKINS-63243] DockerRegistryEndpoint Pattern should accept registry v2 references
  src/main/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpoint.java
  src/test/java/org/jenkinsci/plugins/docker/commons/credentials/DockerRegistryEndpointTest.java
Labels: enhancement

#108 [JENKINS-69432, JENKINS-69436] Revert #86 "docker login - get password from stdin"
  src/main/java/org/jenkinsci/plugins/docker/commons/impl/RegistryKeyMaterialFactory.java
Labels: removed
